// Public data tools + real isolated Node workers. Generated bytes only; no native execution.
import assert from 'node:assert/strict';
import { AsyncLocalStorage } from 'node:async_hooks';
import { createCipheriv, createHash } from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createAnalysisService, defineAnalysisTools } from '../analysis_tools.js';

const scratch = fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()), 'ig5-discovery-host-'));
const cfg = { artifactDir: path.join(scratch, 'artifacts'), defaultEngine: 'ghidra' };
const inline = bytes => ({ encoding: 'hex', data: bytes.toString('hex') });
const sha = bytes => createHash('sha256').update(bytes).digest('hex');
const target = path.join(scratch, 'generated sample.exe');
const session = { target, engine: 'ghidra', artifactId: 'generated-artifact', attachmentId: 'generated-attachment', sha256: 'a'.repeat(64), dbRevision: 3, ready: true, data: Buffer.alloc(2048) };
const mgr = { session, scope: new AsyncLocalStorage(), queue: Promise.resolve(), locked: 0, calls: [],
  checkCancelled() { if (mgr.scope.getStore()?.signal?.aborted) throw Object.assign(new Error('Cancelled'), { code: 'ABORT_ERR' }); },
  get(value, engine) { return path.resolve(value) === session.target && engine === session.engine ? session : undefined; },
  alive(value) { return value?.ready === true; },
  evidence(value) { return { engine: value.engine, artifactId: value.artifactId, attachmentId: value.attachmentId, sha256: value.sha256, dbRevision: value.dbRevision }; },
  withSessions(values, run) { assert.deepEqual(values, [session]); const pending = mgr.queue.catch(() => {}).then(async () => { mgr.locked++; try { return await run(); } finally { mgr.locked--; } }); mgr.queue = pending; return pending; },
  async rpc(value, method, options) { assert.equal(mgr.locked, 1); assert.equal(method, 'bytes'); assert.equal(value, session); mgr.calls.push(options); const at = Number(BigInt(options.ea) - 0x8000000000001000n); return { hex: session.data.subarray(at, at + options.size).toString('hex') }; },
};
const service = createAnalysisService(mgr, cfg); mgr.analysis = service;
const definitions = defineAnalysisTools(mgr, cfg, value => value), tools = new Map(definitions.map(tool => [tool.name, tool]));
const call = (kind, args) => tools.get('ig5_' + kind).execute(args);
const rejects = (run, code) => assert.rejects(run, error => error.code === code);
const cases = [];
async function test(name, body) { try { await body(); cases.push({ name, ok: true }); console.log('PASS', name); } catch (error) { cases.push({ name, ok: false, error: error.stack }); console.error('FAIL', name, error.stack); } }
function frame(id, text) { const payload = Buffer.from(text); const result = Buffer.alloc(payload.length + 7); result.writeUInt16BE(result.length - 2, 0); result[2] = 9; result.writeUInt32BE(id, 3); payload.copy(result, 7); return result; }
const messages = [frame(101, 'first generated payload'), frame(102, 'second generated message'), frame(103, 'third different text payload'), frame(104, 'fourth validation message')];
const clear = Buffer.concat(messages), key = Buffer.from('1956973cb40ea712d88925f6abfe814d', 'hex'), iv = Buffer.from('534b681921fa386408125fed', 'hex'), aad = Buffer.from('IG5 generated discovery');
const enc = createCipheriv('aes-128-gcm', key, iv); enc.setAAD(aad); const cipher = Buffer.concat([enc.update(clear), enc.final()]), tag = enc.getAuthTag();
const material = Buffer.alloc(128, 0x42); key.copy(material, 64); const materialPath = path.join(scratch, 'explicit key material.bin'); fs.writeFileSync(materialPath, material);
cipher.copy(session.data); material.copy(session.data, 1024);
const aes = { kind: 'aes-gcm', iv: inline(iv), tag: inline(tag), aad: inline(aad), padding: 'none' };
const source = (offset, size) => ({ source: { target, engine: 'ghidra', ea: '0x' + (0x8000000000001000n + BigInt(offset)).toString(16), size, expected_revision: 3 } });
let recovered, restored, inferred, keyRef, staticRecovered;
const noSecrets = value => { const text = JSON.stringify(value); for (const bytes of [key, iv, tag, aad, material]) { assert(!text.includes(bytes.toString('hex')), 'Raw key/AES/material leaked in a report'); assert(!text.includes(bytes.toString('base64')), 'Raw key/AES/material leaked in a report'); } };

await test('Existing two tools add recover/infer/ref/delimiter schemas with correct required arrays', async () => {
  assert.equal(definitions.length, 2); assert(tools.get('ig5_crypto').parameters.properties.action.enum.includes('recover'));
  assert(tools.get('ig5_protocol').parameters.properties.action.enum.includes('infer'));
  assert.equal(tools.get('ig5_crypto').parameters.properties.recovery.properties.key_source.properties.source.required[0], 'target');
  assert(tools.get('ig5_protocol').parameters.properties.framing.properties.type.enum.includes('delimiter'));
  function compliant(value) { if (!value || typeof value !== 'object') return; assert.notEqual(value.required, true); if (Object.hasOwn(value, 'required')) assert(Array.isArray(value.required)); for (const item of Object.values(value)) compliant(item); }
  definitions.forEach(tool => compliant(tool.parameters));
});
await test('Real AES-GCM candidate extraction authenticates unknown key material and commits sensitive key refs', async () => {
  recovered = await call('crypto', { action: 'recover', input: inline(cipher), recovery: { method: 'aes-candidates', aes, key_source: { path: materialPath }, material_stride: 16 }, expected: inline(clear) });
  assert.equal(recovered.value.recovery.status, 'verified');
  const candidate = recovered.value.recovery.candidates.find(row => row.keyComplete && row.keyMaterial?.dataRef?.sha256 === sha(key)); assert(candidate);
  keyRef = candidate.keyMaterial.dataRef; assert.equal(keyRef.sensitive, true); assert.equal(keyRef.result_id, recovered.result_id); assert.equal(keyRef.bytes, key.length);
  assert.equal(candidate.keyMaterial.dataHex, undefined); assert.equal(candidate.keyMaterial.previewHex, undefined); assert.deepEqual(service.artifacts.read(keyRef.ref).data, key);
  noSecrets(recovered); noSecrets(service.artifacts.get(recovered.result_id)); noSecrets(await service.list({}));
  assert.equal(recovered.keySource.sha256, sha(material)); assert.equal(recovered.keySource.origin.path, materialPath);
  assert(!fs.existsSync(path.join(service.artifacts.root, 'blobs', sha(material) + '.bin')), 'Whole key-material source must not be persisted');
  assert.deepEqual(fs.readFileSync(materialPath), material);
});
await test('Complete key_ref decrypts without raw key resubmission and preserves producer metadata in historical views', async () => {
  restored = await call('crypto', { action: 'transform', input: { ref: recovered.input.ref, result_id: recovered.result_id }, recipe: { ...aes, key_ref: { ref: keyRef.ref, result_id: keyRef.result_id } }, expected: inline(clear) });
  assert.equal(restored.value.verification.matched, true); assert.equal(restored.value.authentication.status, 'passed'); assert.equal(restored.output.sha256, sha(clear));
  const past = await call('crypto', { action: 'result', result_id: restored.result_id }); assert.equal(past.keySource.result_id, recovered.result_id);
  noSecrets(restored); noSecrets(past); noSecrets(service.artifacts.get(restored.result_id));
  const selected = await call('crypto', { action: 'result', result_id: recovered.result_id, select: 'recovery.candidates.0.keyMaterial' }); noSecrets(selected); assert.equal(selected.value.previewHex, undefined);
});
await test('Producer-marked keys reject ordinary analysis previews while controlled key_source and legacy unbound reads stay explicit', async () => {
  const bound = { ref: keyRef.ref, result_id: recovered.result_id };
  for (const kind of ['crypto', 'protocol']) await rejects(() => call(kind, { action: 'inspect', input: bound }), 'KEY_REF_AS_DATA');
  await rejects(() => call('crypto', { action: 'transform', input: bound, recipe: { kind: 'xor', key: inline(Buffer.from([1])) } }), 'KEY_REF_AS_DATA');
  const reused = await call('crypto', { action: 'recover', input: { ref: recovered.input.ref, result_id: recovered.result_id }, recovery: { method: 'aes-candidates', aes, key_source: bound } });
  assert.equal(reused.value.recovery.status, 'verified'); assert.equal(reused.keySource.origin.derivedFrom.resultId, recovered.result_id); noSecrets(reused); noSecrets(service.artifacts.get(reused.result_id));
  // Compatibility deliberately keeps explicit raw reads without a producer. This is a
  // role-aware automatic-preview guard, not an ACL for files the local user owns.
  const unbound = await call('crypto', { action: 'inspect', input: { ref: keyRef.ref } });
  assert.equal(unbound.association, undefined); assert.equal(unbound.value.input.preview.hex, key.toString('hex')); assert.match(unbound.note, /not a local secret access-control boundary/);
});
await test('Partial/contradictory masks, ordinary blobs and foreign producer refs cannot be executed as keys', async () => {
  const partial = service.artifacts.save({ kind: 'crypto', action: 'recover', result: { recovery: { candidates: [{ keyComplete: false, keyMaterial: { keyComplete: false, dataRef: { ...keyRef, sensitive: true }, known_mask: '01'.repeat(15) + '00', unknown_mask: '00'.repeat(15) + '01' } }] } } });
  const badMasks = service.artifacts.save({ kind: 'crypto', action: 'recover', result: { recovery: { candidates: [{ keyComplete: true, keyMaterial: { keyComplete: true, dataRef: keyRef, known_mask: '00'.repeat(16), unknown_mask: '00'.repeat(16) } }] } } });
  for (const producer of [partial.id, badMasks.id, restored.result_id]) await rejects(() => call('crypto', { action: 'transform', input: inline(cipher), recipe: { ...aes, key_ref: { ref: keyRef.ref, result_id: producer } } }), 'INVALID_KEY_REF');
  await rejects(() => call('crypto', { action: 'transform', input: inline(cipher), recipe: { ...aes, key_ref: { ref: restored.output.ref, result_id: recovered.result_id } } }), 'INVALID_KEY_REF');
  await rejects(() => call('crypto', { action: 'transform', input: inline(cipher), recipe: { ...aes, key: inline(key), key_ref: { ref: keyRef.ref, result_id: recovered.result_id } } }), 'INVALID_KEY_REF');
});
await test('Static ciphertext and key-source captures use serialized read-only queue and identical sample provenance', async () => {
  staticRecovered = await call('crypto', { action: 'recover', input: source(0, cipher.length), recovery: { method: 'aes-candidates', aes, key_source: source(1024, material.length) } });
  assert.equal(staticRecovered.value.recovery.status, 'verified'); assert.equal(staticRecovered.association.sha256, session.sha256);
  assert.equal(staticRecovered.keySource.association.attachmentId, session.attachmentId); assert.equal(mgr.calls.length, 2); assert.equal(session.dbRevision, 3); noSecrets(staticRecovered);
  const candidate = staticRecovered.value.recovery.candidates[0];
  const result = await call('crypto', { action: 'transform', input: { ref: staticRecovered.input.ref, result_id: staticRecovered.result_id }, recipe: { ...aes, key_ref: { ref: candidate.keyMaterial.dataRef.ref, result_id: staticRecovered.result_id } } });
  assert.equal(result.output.sha256, sha(clear)); assert.equal(result.association.dbRevision, 3);
});
await test('Key source cannot silently attach to another target, engine, sample hash or revision', async () => {
  await rejects(() => call('crypto', { action: 'recover', input: inline(cipher), recovery: { method: 'aes-candidates', aes, key_source: source(1024, material.length) } }), 'ASSOCIATION_CONFLICT');
  const base = service.artifacts.get(staticRecovered.result_id);
  for (const difference of [{ target: path.join(scratch, 'other.exe') }, { engine: 'reverse' }, { sha256: 'b'.repeat(64) }, { dbRevision: 4 }, { attachmentId: 'other-attachment' }]) {
    const corrected = service.artifacts.save({ kind: 'crypto', action: 'recover', association: { ...base.association, ...difference }, input: base.input, result: base.result });
    await rejects(() => call('crypto', { action: 'transform', input: { ref: staticRecovered.input.ref, result_id: staticRecovered.result_id }, recipe: { ...aes, key_ref: { ref: keyRef.ref, result_id: corrected.id } } }), 'ASSOCIATION_CONFLICT');
  }
});
await test('Wrong actions, conflicting key sources and oversized material/budgets fail without secrets in errors', async () => {
  await rejects(() => call('crypto', { action: 'inspect', input: inline(cipher), recovery: { method: 'auto' } }), 'INVALID_INPUT');
  await rejects(() => call('protocol', { action: 'decode', input: inline(clear), inference: {} }), 'INVALID_INPUT');
  await rejects(() => call('protocol', { action: 'infer', input: inline(clear), schema: { fields: [] } }), 'INVALID_INPUT');
  await rejects(() => call('crypto', { action: 'recover', input: inline(cipher), recovery: { key_source: { path: materialPath }, key_material: inline(material) } }), 'INVALID_INPUT');
  const oversized = path.join(scratch, 'oversized key material.bin'); fs.writeFileSync(oversized, Buffer.alloc(65537));
  await rejects(() => call('crypto', { action: 'recover', input: inline(cipher), recovery: { key_source: { path: oversized } } }), 'INPUT_LIMIT');
  for (const recovery of [{ method: 'aes-candidates', aes, key_candidates: [inline(key)], max_trials: 4097 }, { method: 'aes-candidates', aes, key_material: inline(material), max_work_bytes: 67108865 }]) {
    try { await call('crypto', { action: 'recover', input: inline(cipher), recovery }); assert.fail('Expected bounded input rejection'); } catch (error) { assert.notEqual(error.code, 'ERR_ASSERTION'); noSecrets({ message: error.message }); }
  }
});
await test('Unknown single and repeating XOR keys recover into reusable complete references', async () => {
  const text = Buffer.from('This generated message contains clear protocol data for this key recovery test. The message is readable and the verification is exact.');
  for (const bytes of [Buffer.from([0xb6]), Buffer.from('c8410fab79', 'hex')]) {
    const encrypted = Buffer.from(text, value => value); for (let index = 0; index < encrypted.length; index++) encrypted[index] ^= bytes[index % bytes.length];
    const result = await call('crypto', { action: 'recover', input: inline(encrypted), expected: inline(text), recovery: { method: bytes.length === 1 ? 'xor-single' : 'xor-repeat', key_lengths: [bytes.length], known_plaintext: [{ offset: 0, ...inline(text.subarray(0, 10)) }] } });
    assert.equal(result.value.recovery.status, 'verified'); const candidate = result.value.recovery.candidates.find(row => row.keyMaterial?.dataRef?.sha256 === sha(bytes)); assert(candidate);
    assert.equal(candidate.keyMaterial.previewHex, undefined); assert.equal(candidate.keyMaterial.dataHex, undefined);
    const decoded = await call('crypto', { action: 'transform', input: { ref: result.input.ref, result_id: result.result_id }, recipe: { kind: 'xor', key_ref: { ref: candidate.keyMaterial.dataRef.ref, result_id: result.result_id } }, expected: inline(text) });
    assert.equal(decoded.value.verification.matched, true); assert.equal(decoded.output.sha256, sha(text));
  }
});
await test('Real recovered plaintext infers length framing using independent held-out messages', async () => {
  inferred = await call('protocol', { action: 'infer', input: { ref: restored.output.ref, result_id: restored.result_id }, inference: { format: 'messages', samples: messages.slice(0, 3).map(inline), holdout_samples: [inline(messages[3])], boundary: 'message-start', min_frames: 3 } });
  const candidate = inferred.value.inference.candidates.find(row => row.framing.type === 'length-prefix' && row.framing.size === 2 && row.framing.endian === 'big' && row.validation.verified);
  assert(candidate, 'Independent length-prefix candidate absent');
  assert.equal(candidate.validation.status, 'passed'); assert.equal(inferred.input.ref, restored.output.ref);
  const decoded = await call('protocol', { action: 'decode', input: { ref: restored.output.ref, result_id: restored.result_id }, framing: candidate.framing, schema: candidate.schema });
  assert.equal(decoded.value.complete, true); assert.equal(decoded.value.frames.length, 4); assert.deepEqual(decoded.value.frames.map(row => row.length), messages.map(row => row.length));
});
await test('Unknown boundary, insufficient evidence and non-independent validation retain uncertainty', async () => {
  const unknown = await call('protocol', { action: 'infer', input: inline(clear), inference: { format: 'stream', boundary: 'unknown' } });
  assert(!service.artifacts.get(unknown.result_id).result.inference.candidates.some(row => row.validation?.verified));
  const short = await call('protocol', { action: 'infer', input: inline(Buffer.from([1, 2, 3])) }); assert.notEqual(short.value.inference.status, 'verified');
  const duplicates = await call('protocol', { action: 'infer', input: inline(clear), inference: { format: 'messages', samples: messages.slice(0, 3).map(inline), holdout_samples: [inline(messages[0])] } });
  assert(!service.artifacts.get(duplicates.result_id).result.inference.candidates.some(row => row.validation?.verified));
});
await test('Inferred delimiter framing decodes without hidden active capture or network calls', async () => {
  const text = Buffer.from('TYPE one\nTYPE two longer\nTYPE three long\n');
  const found = await call('protocol', { action: 'infer', input: inline(text), inference: { format: 'stream', boundary: 'message-start' } });
  const candidate = found.value.inference.candidates.find(row => row.framing.type === 'delimiter' && row.framing.delimiterHex === '0a'); assert(candidate);
  const decoded = await call('protocol', { action: 'decode', input: { ref: found.input.ref, result_id: found.result_id }, framing: candidate.framing, schema: candidate.schema });
  assert.equal(decoded.value.frames.length, 3); assert.equal(decoded.value.complete, true);
});
await test('Inference combined sample/scan/work budgets reject overrun and truncated summaries remain explicit', async () => {
  for (const inference of [{ max_work: 2000001 }, { max_scan_bytes: 262145 }, { min_frames: 2 }, { samples: Array(64).fill(inline(messages[0])), holdout_samples: [inline(messages[3])] }]) await rejects(() => call('protocol', { action: 'infer', input: inline(clear), inference }), 'INVALID_PROTOCOL_ARGUMENT');
  const budgeted = await call('protocol', { action: 'infer', input: inline(clear), inference: { format: 'stream', boundary: 'message-start', max_work: 1 } });
  assert.equal(budgeted.value.inference.budget.exhausted, true); assert.notEqual(budgeted.value.inference.status, 'verified');
  for (const entry of (await service.list({ limit: 100 })).items) noSecrets(entry);
});
await test('Unknown prefix inference feeds exact decodeInput range into decode while retaining the original reference', async () => {
  const prefix = Buffer.from('fffefdfcfb', 'hex'), tail = Buffer.from('000c', 'hex');
  const stream = Buffer.concat([prefix, clear, tail]);
  const parent = await call('crypto', { action: 'inspect', input: inline(stream), target, engine: 'ghidra' });
  const inferred = await call('protocol', { action: 'infer', input: { ref: parent.input.ref, result_id: parent.result_id }, inference: { format: 'stream', boundary: 'unknown', holdout_samples: [inline(frame(201, 'independent alignment validation payload'))] } });
  const candidate = service.artifacts.get(inferred.result_id).result.inference.candidates.find(row => row.framing.type === 'length-prefix' && row.framing.offset === 0 && row.framing.size === 2 && row.framing.endian === 'big' && row.decodeInput?.startOffset === prefix.length);
  assert(candidate); assert.equal(candidate.decodeInput.byteLength, clear.length); assert.equal(candidate.evidence.trailingBytes, tail.length);
  const decoded = await call('protocol', { action: 'decode', input: { ref: inferred.input.ref, result_id: inferred.result_id }, offset: candidate.decodeInput.startOffset, length: candidate.decodeInput.byteLength, framing: candidate.framing, schema: candidate.schema });
  assert.equal(decoded.value.complete, true); assert.equal(decoded.value.frames.length, 4); assert.equal(decoded.input.sha256, sha(clear));
  assert.equal(decoded.input.origin.ref, inferred.input.ref); assert.equal(decoded.input.origin.range.offset, 5); assert.equal(decoded.input.origin.range.length, clear.length);
  assert.equal(decoded.input.origin.range.sourceBytes, stream.length); assert.equal(decoded.input.origin.range.sourceSha256, sha(stream)); assert.deepEqual(decoded.association, inferred.association);
  assert.deepEqual(service.artifacts.read(inferred.input.ref).data, stream);
  for (const range of [{ offset: -1 }, { offset: stream.length + 1 }, { offset: 1.5 }, { length: -1 }, { length: stream.length + 1 }, { offset: Number.MAX_SAFE_INTEGER + 1 }, { offset: 5, length: stream.length }]) await rejects(() => call('protocol', { action: 'inspect', input: { ref: inferred.input.ref, result_id: inferred.result_id }, ...range }), 'INVALID_INPUT');
  await rejects(() => call('protocol', { action: 'result', result_id: inferred.result_id, offset: 0 }), 'INVALID_INPUT');
  const tooLarge = path.join(scratch, 'large source.bin'); fs.writeFileSync(tooLarge, Buffer.alloc(8 * 1024 * 1024 + 1)); await rejects(() => call('protocol', { action: 'inspect', input: { path: tooLarge }, offset: 0, length: 1 }), 'INPUT_LIMIT');
});
await test('Eight full 1 MiB candidate payloads plus 32-byte keys fit separate bounded artifact budgets', async () => {
  const boundary = createAnalysisService(mgr, { ...cfg, artifactDir: path.join(scratch, 'boundary-artifacts') });
  // Isolate host artifact accounting from algorithm candidate selection; real worker chains above
  // already exercise execution. Eight different maximal payloads must not fail due to key bytes.
  const candidates = Array.from({ length: 8 }, (_, index) => ({ keyComplete: true,
    keyMaterial: { dataHex: Buffer.alloc(32, index + 1).toString('hex'), keyComplete: true, known_mask: '01'.repeat(32), unknown_mask: '00'.repeat(32) },
    plaintext: { dataHex: Buffer.alloc(1024 * 1024, index + 1).toString('hex'), length: 1024 * 1024 } }));
  boundary.jobs.run = async () => ({ result: { recovery: { status: 'candidate', candidates } }, output: null });
  try {
    const result = await boundary.execute('crypto', { action: 'recover', input: inline(cipher) });
    const full = boundary.artifacts.get(result.result_id); assert.equal(full.result.recovery.candidates.length, 8);
    assert.equal(full.result.recovery.candidates.reduce((sum, row) => sum + row.plaintext.dataRef.bytes, 0), 8 * 1024 * 1024);
    assert.equal(full.result.recovery.candidates.reduce((sum, row) => sum + row.keyMaterial.dataRef.bytes, 0), 256);
    assert(JSON.stringify(result.value).length <= 20000); assert(full.result.recovery.candidates.every(row => row.keyMaterial.previewHex === undefined));
    candidates.push(candidates[0]); await rejects(() => boundary.execute('crypto', { action: 'recover', input: inline(cipher) }), 'RESULT_LIMIT');
  } finally { await boundary.dispose(); }
});

await test('Public framing schemas execute canonical varint and TLV inference-to-decode with independent holdout', async () => {
  const schema = tools.get('ig5_protocol').parameters.properties.framing.properties;
  assert(schema.type.enum.includes('varint-prefix')); assert(schema.type.enum.includes('tlv')); assert.equal(schema.maxBytes.maximum, 5);
  const leb = n => { const bytes = []; do { const byte = n & 127; n >>>= 7; bytes.push(byte | (n ? 128 : 0)); } while (n); return Buffer.from(bytes); };
  const wrapVarint = text => { const bytes = Buffer.from(text); return Buffer.concat([leb(bytes.length), bytes]); };
  const wrapTlv = (tag, text) => { const bytes = Buffer.from(text); return Buffer.concat([Buffer.from([tag, bytes.length]), bytes]); };
  for (const [type, samples, holdout] of [
    ['varint-prefix', ['short varint', 'long varint '.repeat(12), 'third body'].map(wrapVarint), wrapVarint('separate holdout payload')],
    ['tlv', [wrapTlv(1, 'one'), wrapTlv(2, 'second payload'), wrapTlv(3, 'three bytes')], wrapTlv(4, 'fourth unseen message')],
  ]) {
    const stream = Buffer.concat(samples), found = await call('protocol', { action: 'infer', input: inline(stream), inference: { format: 'stream', boundary: 'message-start', holdout_samples: [inline(holdout)] } });
    const candidate = service.artifacts.get(found.result_id).result.inference.candidates.find(row => row.framing.type === type && row.decodeInput.startOffset === 0);
    assert(candidate, `${type} candidate missing`); assert.equal(candidate.validation.verified, true);
    const decoded = await call('protocol', { action: 'decode', input: { ref: found.input.ref, result_id: found.result_id }, offset: candidate.decodeInput.startOffset, length: candidate.decodeInput.byteLength, framing: candidate.framing, schema: candidate.schema });
    assert.equal(decoded.value.complete, true); assert.equal(decoded.value.frames.length, 3);
  }
});
await test('Chinese XOR candidates reuse sensitive refs and archived reports remain executable without claiming verification', async () => {
  const plain = Buffer.from('这是生成的中文协议消息，包含用户配置、数据分析和测试内容。'.repeat(5)), ciphertext = Buffer.from(plain.map(value => value ^ 0x71));
  const found = await call('crypto', { action: 'recover', input: inline(ciphertext), recovery: { method: 'xor-single' } });
  const candidate = service.artifacts.get(found.result_id).result.recovery.candidates[0];
  assert.equal(candidate.status, 'candidate'); assert.equal(found.output, undefined);
  assert.equal((await service.history({ action: 'archive', ids: [found.result_id] })).ok, true);
  assert((await service.list({ archived: true })).items.some(row => row.id === found.result_id));
  const decoded = await call('crypto', { action: 'transform', input: { ref: found.input.ref, result_id: found.result_id }, recipe: { kind: 'xor', key_ref: { ref: candidate.keyMaterial.dataRef.ref, result_id: found.result_id } }, expected: inline(plain) });
  assert.deepEqual(service.artifacts.read(decoded.output.ref).data, plain);
  assert.equal((await service.history({ action: 'restore', ids: [found.result_id] })).ok, true);
});

await service.dispose();
const report = { ok: cases.every(item => item.ok), tests: cases, artifacts: scratch, nativeEnginesExecuted: false, generatedSamplesOnly: true };
fs.writeFileSync(path.join(scratch, 'acceptance.json'), JSON.stringify(report, null, 2)); console.log('Discovery host acceptance:', scratch);
if (!report.ok) process.exitCode = 1;
